logging:
  level:
    io.r2dbc.postgresql.QUERY: ${R2DBC_LOGGING:INFO} # for queries
    io.r2dbc.postgresql.PARAM: ${R2DBC_LOGGING:INFO} # for parameters

springdoc:
  swagger-ui:
    path: /swagger
    enabled: ${SWAGGER:false}

server:
  error:
    include-message: always

spring:
  # Настройка базы данных
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/monitoring
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  # Настройка миграции базы данных
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/monitoring
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  # Настройка json
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+8"
  # Настройка почты
  mail:
    host: ${SMTP_HOST:smtp.new-servers.ru}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 465
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 500
          ssl:
            enable: true
            trust: "*"
    # Настройки токена для отправления в сообщениях почты
    # (чтобы подтверждать регистрацию и смену пароля)
    jwt:
      secret: ${MAIL_SECRET}
      expiration: 3600

security:
  # Настройки хеширования паролей
  bcrypt:
    version: 2a
    strength: 10
  # Настройки jwt токенов для авторизации
  jwt:
    secret: ${JWT_SECRET}
    expiration: 28800
  # Время в секундах, через которое можно повторно восстановить пароль пользователю
  restore_seconds_limit: 3600

# Настройки webclient
webclient:
  connect-timeout: 5000
  read-timeout: 5000
  write-timeout: 5000
  buffer-size: 20971520

# Настройки recaptcha
google:
  recaptcha:
    key:
      site: ${RECAPTCHA_SITE}
      secret: ${RECAPTCHA_SECRET}

monitoring:
  # Время в секундах, через которое можно повторно добавить пользователю сервер в список
  server_seconds_limit: 1200

backends:
  # URL пингера
  pinger-url: http://${PINGER_HOST}
  # Не используется на данный момент
  bridge-url: http://${BRIDGE_HOST}